# pull official base image
# FROM node:13.12.0-alpine
FROM node:latest

RUN mkdir -p /usr/src/app

# set working directory
WORKDIR /usr/src/app

# add `/app/node_modules/.bin` to $PATH
# ENV PATH /app/node_modules/.bin:$PATH


COPY package.json /usr/src/app

RUN echo "npm install"
RUN npm install
RUN echo "npm install COMPLETED"
ADD src /usr/src/app/src
ADD public /usr/src/app/public
RUN echo "npm build"
RUN npm build
RUN echo "npm build COMPLETED"
CMD ["npm", "start"]
RUN echo "END"